Upudate CH Translate
xChillax/PZBetterMoodlesDescriptions pull request #4
Opened 2023-02-19 09:32 UTC by Genshin804

fix Other state value
Add Angry state

2023-02-19 16:13 UTC, xChillax requested changes
Looks good! Just one tiny issue and it should be good merge!

2023-02-19 16:13 UTC, xChillax commented on CH/Moodles_CH.txt
> +	Moodles_hyperthermia_desc_lvl2 = "體温39°C<<br>口渴值/疲勞度上升<br>-34%攻速<br>-34%移速",
```suggestion
	Moodles_hyperthermia_desc_lvl2 = "體温39°C<br>口渴值/疲勞度上升<br>-34%攻速<br>-34%移速",
```

2023-02-19 18:46 UTC, Genshin804 commented
> Looks good! Just one tiny issue and it should be good to merge!

2023-02-20 23:08 UTC, xChillax approved these changes

2023-02-20 23:09 UTC, merged